#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#

# Builds and runs qpid-dispatch-router in a container.
#
# This build script assumes that the router config file is present at
# the top level of the build context.  This can be overridden using
# the config_path build argument.

FROM fedora:latest
LABEL maintainer=kgiusti@gmail.com

#
# Build arguments:
#   proton_branch - git branch/tag name of proton source
#   proton_url - git url to proton repo
#   dispatch_branch - git branch/tag name of qdrouterd source
#   dispatch_url - git url to qdrouterd repo
#   config_file - qdrouterd config file to use

ARG proton_branch
ARG proton_url
ARG dispatch_branch
ARG dispatch_url
ARG config_file

ENV proton_branch ${proton_branch:-master}
ENV proton_url ${proton_url:-https://gitbox.apache.org/repos/asf/qpid-proton.git}
ENV dispatch_branch ${dispatch_branch:-master}
ENV dispatch_url ${dispatch_url:-https://gitbox.apache.org/repos/asf/qpid-dispatch.git}
ENV config_file ${config_file:-qdrouterd.conf}


# Install all the required packages. Some in this list were picked off
#  from proton's INSTALL.md
#  (https://github.com/apache/qpid-proton/blob/master/INSTALL.md) and
#  the rest are from dispatch
#  (https://github.com/apache/qpid-dispatch/blob/master/README)

RUN dnf -y install \
    gcc \
    gcc-c++ \
    cmake \
    openssl-devel \
    cyrus-sasl-devel \
    cyrus-sasl-plain \
    cyrus-sasl-gssapi \
    cyrus-sasl-md5 \
    swig \
    python-devel \
    make \
    libuv \
    libuv-devel \
    libwebsockets-devel \
    git \
    && dnf clean all -y

# Create a main directory for building proton and dispatch router
#
WORKDIR /main

# build and install proton from ${proton_branch} on ${proton_url}
#
RUN git clone --branch ${proton_branch} --single-branch --depth 1 ${proton_url} qpid-proton \
    && cd qpid-proton \
    && mkdir BUILD \
    && cd BUILD \
    && cmake .. -DSYSINSTALL_BINDINGS=ON -DCMAKE_INSTALL_PREFIX=/usr -DSYSINSTALL_PYTHON=ON \
                -DBUILD_BINDINGS=python -DCMAKE_BUILD_TYPE=RelWithDebInfo \
    && make install \
    && cd /main \
    && rm -rf qpid-proton

# build and install dispatch from ${dispatch_branch} on ${dispatch_url}
#
RUN git clone --branch ${dispatch_branch} --single-branch --depth 1 ${dispatch_url} qpid-dispatch \
    && cd qpid-dispatch \
    && mkdir BUILD \
    && cd BUILD \
    && cmake .. -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE=Debug \
    && make install \
    && cd /main \
    && rm -rf qpid-dispatch

# move the configuration file in place
#
COPY ${config_file} /etc/qpid-dispatch/qdrouterd.conf

# Start the dispatch router
#
CMD ["qdrouterd"]
